import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig, devices } from '@playwright/test';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Placeholder fixtures generated by e2e/fixtures/generate-fixtures.mjs — see
// e2e/README.md for what's real vs. placeholder today.
const TONE_FIXTURE = path.resolve(__dirname, 'e2e/fixtures/placeholder-tone.wav');
const SILENCE_FIXTURE = path.resolve(__dirname, 'e2e/fixtures/silence.wav');

// A real, hand-recorded speech fixture (mono 16-bit PCM WAV, 16kHz — same
// format `backend/tests/fixtures/real_audio/` expects, since it's the same
// Deepgram-facing pipeline underneath). Not committed (it's a real
// recording of a real person) and not generated by any script — see
// e2e/README.md for how to add one. Read at config-load time (this file
// runs once per `playwright test` invocation, not per-test), so dropping
// the file in and re-running is all that's needed to switch both fake-mic
// projects over to it automatically.
const REAL_SPEECH_FIXTURE = path.resolve(__dirname, 'e2e/fixtures/real-speech.wav');
export const HAS_REAL_SPEECH_FIXTURE = existsSync(REAL_SPEECH_FIXTURE);
const SPEECH_FIXTURE = HAS_REAL_SPEECH_FIXTURE ? REAL_SPEECH_FIXTURE : TONE_FIXTURE;

// A deliberately non-default port, not Vite's usual 5173: reuseExistingServer
// (below) trusts *any* already-listening server at the target URL, and this
// machine can have unrelated dev servers left running on the common port
// from other work. --strictPort makes `vite` fail loudly instead of picking
// a different port silently if this one's ever unexpectedly taken too.
const PORT = 5183;
const BASE_URL = `http://localhost:${PORT}`;

// Chrome's fake-mic launch args (per-project below): auto-grants a fake
// microphone device and feeds it audio from a local .wav file instead of a
// real mic — this is what makes the E2E specs exercise the actual
// getUserMedia() -> capture -> STT path instead of mocking it out.
// `--use-file-for-fake-audio-capture` is fixed per browser process, so a
// separate project (one Chromium instance each) is used per fixture file
// rather than trying to swap it mid-run.
//
// `--use-fake-ui-for-media-stream` is required alongside
// `--use-fake-device-for-media-stream` in Chromium's headless mode
// specifically — confirmed by hand in this environment: without it,
// getUserMedia() rejects every call with `NotSupportedError` under
// `chromium.launch({ headless: true })` (Playwright's default) even though
// Playwright's own `permissions: ['microphone']` context option grants the
// permission via CDP. Both flags together work in headless and headed mode
// alike; `permissions: ['microphone']` is kept too since it's what actually
// grants the permission Playwright-side.
function fakeMicArgs(audioFixturePath: string): string[] {
  return [
    '--use-fake-device-for-media-stream',
    '--use-fake-ui-for-media-stream',
    `--use-file-for-fake-audio-capture=${audioFixturePath}`,
  ];
}

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  // Serial-ish worker count: each project below launches its own Chromium
  // process with fake-mic flags baked in at launch time, so there's no
  // sharing/contention concern — this just keeps local runs predictable.
  workers: process.env.CI ? 2 : undefined,
  reporter: [['html', { open: 'never' }]],
  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
  },
  // Two servers: Vite dev (not `vite preview` — the fake-mic flow depends on
  // the AudioWorklet module served from public/, see cascadeConfig.ts's
  // CASCADE_PCM_WORKLET_URL, which behaves identically in dev and preview
  // here, so dev's faster startup wins with nothing traded away) plus the
  // FastAPI backend, so a live run (real fixture + real API keys in
  // backend/.env) only needs `npx playwright test`, not two terminals
  // started by hand first. `reuseExistingServer` means this is also exactly
  // as convenient when both are already running from local dev.
  webServer: [
    {
      command: `npm run dev -- --port ${PORT} --strictPort`,
      url: BASE_URL,
      reuseExistingServer: !process.env.CI,
      timeout: 30_000,
    },
    {
      command: 'uv run uvicorn app.main:app --port 8000',
      cwd: path.resolve(__dirname, '../backend'),
      url: 'http://localhost:8000/health',
      reuseExistingServer: !process.env.CI,
      timeout: 30_000,
    },
  ],
  projects: [
    {
      name: 'realtime-fake-mic',
      testMatch: /realtime\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        permissions: ['microphone'],
        launchOptions: { args: fakeMicArgs(SPEECH_FIXTURE) },
      },
    },
    {
      name: 'cascade-fake-mic',
      testMatch: /cascade\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        permissions: ['microphone'],
        launchOptions: { args: fakeMicArgs(SPEECH_FIXTURE) },
      },
    },
    {
      name: 'observability',
      testMatch: /observability\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
});
