import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig, devices } from '@playwright/test';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Placeholder fixtures generated by e2e/fixtures/generate-fixtures.mjs — see
// e2e/README.md for what's real vs. placeholder today. Swap these for the
// backend's TTS-generated speech fixtures once they exist; nothing else in
// this config needs to change to pick them up.
const TONE_FIXTURE = path.resolve(__dirname, 'e2e/fixtures/placeholder-tone.wav');
const SILENCE_FIXTURE = path.resolve(__dirname, 'e2e/fixtures/silence.wav');

// A deliberately non-default port, not Vite's usual 5173: reuseExistingServer
// (below) trusts *any* already-listening server at the target URL, and this
// machine can have unrelated dev servers left running on the common port
// from other work. --strictPort makes `vite` fail loudly instead of picking
// a different port silently if this one's ever unexpectedly taken too.
const PORT = 5183;
const BASE_URL = `http://localhost:${PORT}`;

// Chrome's fake-mic launch args (per-project below): auto-grants a fake
// microphone device and feeds it audio from a local .wav file instead of a
// real mic — this is what makes the E2E specs exercise the actual
// getUserMedia() -> capture -> STT path instead of mocking it out.
// `--use-file-for-fake-audio-capture` is fixed per browser process, so a
// separate project (one Chromium instance each) is used per fixture file
// rather than trying to swap it mid-run.
//
// `--use-fake-ui-for-media-stream` is required alongside
// `--use-fake-device-for-media-stream` in Chromium's headless mode
// specifically — confirmed by hand in this environment: without it,
// getUserMedia() rejects every call with `NotSupportedError` under
// `chromium.launch({ headless: true })` (Playwright's default) even though
// Playwright's own `permissions: ['microphone']` context option grants the
// permission via CDP. Both flags together work in headless and headed mode
// alike; `permissions: ['microphone']` is kept too since it's what actually
// grants the permission Playwright-side.
function fakeMicArgs(audioFixturePath: string): string[] {
  return [
    '--use-fake-device-for-media-stream',
    '--use-fake-ui-for-media-stream',
    `--use-file-for-fake-audio-capture=${audioFixturePath}`,
  ];
}

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  // Serial-ish worker count: each project below launches its own Chromium
  // process with fake-mic flags baked in at launch time, so there's no
  // sharing/contention concern — this just keeps local runs predictable.
  workers: process.env.CI ? 2 : undefined,
  reporter: [['html', { open: 'never' }]],
  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
  },
  // Vite dev server, not `vite preview` against a production build: the
  // fake-mic flow depends on the AudioWorklet module served from public/
  // (see cascadeConfig.ts's CASCADE_PCM_WORKLET_URL) and on
  // VITE_API_BASE_URL resolution, both of which behave identically in dev
  // and preview here — dev's faster startup wins with nothing traded away.
  webServer: {
    command: `npm run dev -- --port ${PORT} --strictPort`,
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 30_000,
  },
  projects: [
    {
      name: 'realtime-fake-mic',
      testMatch: /realtime\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        permissions: ['microphone'],
        launchOptions: { args: fakeMicArgs(TONE_FIXTURE) },
      },
    },
    {
      name: 'cascade-fake-mic',
      testMatch: /cascade\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        permissions: ['microphone'],
        launchOptions: { args: fakeMicArgs(TONE_FIXTURE) },
      },
    },
    {
      name: 'noise-rejection-fake-mic',
      testMatch: /noise-rejection\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        permissions: ['microphone'],
        launchOptions: { args: fakeMicArgs(SILENCE_FIXTURE) },
      },
    },
  ],
});
